<?php
/**
 * UnionIDSignInRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ZSGF\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ZSGF\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UnionIDSignInRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UnionIDSignInRequest
 * @package     ZSGF\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UnionIDSignInRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UnionIDSignInRequest"
     */
    public function testUnionIDSignInRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "union_id"
     */
    public function testPropertyUnionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "two_factor_code"
     */
    public function testPropertyTwoFactorCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
