<?php
/**
 * AppApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ZSGF\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ZSGF\Client\Test\Api;

use \ZSGF\Client\Configuration;
use \ZSGF\Client\ApiException;
use \ZSGF\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppApiTest Class Doc Comment
 *
 * @category Class
 * @package  ZSGF\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for app
     *
     * 应用详情.
     *
     */
    public function testApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for app2FA
     *
     * 双因素验证 获取.
     *
     */
    public function testApp2FA()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for app2FACheck
     *
     * 双因素验证 验证.
     *
     */
    public function testApp2FACheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appCheckVersion
     *
     * 更新应用数据库.
     *
     */
    public function testAppCheckVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appDelete
     *
     * 删除应用.
     *
     */
    public function testAppDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appInfo
     *
     * 应用详情.
     *
     */
    public function testAppInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appPost
     *
     * 创建应用.
     *
     */
    public function testAppPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appPut
     *
     * 更新应用.
     *
     */
    public function testAppPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appTransfer
     *
     * 转移应用.
     *
     */
    public function testAppTransfer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apps
     *
     * 应用列表.
     *
     */
    public function testApps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
